name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*' # v1.0.0などのタグがプッシュされたときに実行

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish Module A and Module B
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHubが自動発行するトークン
        run: |
          # 各モジュールの publishReleasePublicationToGitHubPackagesRepository を実行
          ./gradlew :chobilib:publishReleasePublicationToGitHubPackagesRepository
          ./gradlew :admob:publishReleasePublicationToGitHubPackagesRepository
